[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13.4"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.17"
prost-types = "0.13"
tonic = "0.12.3"
nanoid = "0.4.0"
local-ip-address = "0.6.3"

[build-dependencies]
tonic-build = "0.12.3"

